<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-03-09T15:11:33 EET" name="Default suite" finished-at="2020-03-09T15:12:24 EET" duration-ms="50651">
    <groups>
    </groups>
    <test started-at="2020-03-09T15:11:33 EET" name="Default test" finished-at="2020-03-09T15:12:24 EET" duration-ms="50651">
      <class name="test.TestCases">
        <test-method is-config="true" signature="BeforeMethod()[pri:0, instance:test.TestCases@ec756bd]" started-at="2020-03-09T15:11:33 EET" name="BeforeMethod" finished-at="2020-03-09T15:11:46 EET" duration-ms="12693" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeMethod -->
        <test-method signature="SiteTest()[pri:1, instance:test.TestCases@ec756bd]" started-at="2020-03-09T15:11:46 EET" name="SiteTest" finished-at="2020-03-09T15:11:48 EET" duration-ms="1555" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SiteTest -->
        <test-method signature="LoginTest()[pri:2, instance:test.TestCases@ec756bd]" started-at="2020-03-09T15:11:48 EET" name="LoginTest" finished-at="2020-03-09T15:11:51 EET" duration-ms="3841" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTest -->
        <test-method signature="SearchTest()[pri:3, instance:test.TestCases@ec756bd]" started-at="2020-03-09T15:11:51 EET" name="SearchTest" finished-at="2020-03-09T15:12:13 EET" duration-ms="21484" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchTest -->
        <test-method signature="BasketTest()[pri:4, instance:test.TestCases@ec756bd]" started-at="2020-03-09T15:12:13 EET" name="BasketTest" finished-at="2020-03-09T15:12:13 EET" duration-ms="324" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found []
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:563)
at test.TestCases.BasketTest(TestCases.java:84)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BasketTest -->
        <test-method is-config="true" signature="AfterMethod()[pri:0, instance:test.TestCases@ec756bd]" started-at="2020-03-09T15:12:13 EET" name="AfterMethod" finished-at="2020-03-09T15:12:24 EET" duration-ms="10684" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
      </class> <!-- test.TestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
